### PR TITLE
Parallel workers and look up data url

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by andylolz** [comment]
Could you say a bit about what this is, @Bjwebb? Does it relate to #27?

**Comment by Bjwebb** [comment]
> Could you say a bit about what effect the parallel workers change has, @Bjwebb? Does it relate to https://github.com/codeforIATI/IATI-Stats/issues/27?

Yes it's relevant to that, but I've been looking at it as part of https://github.com/codeforIATI/IATI-Stats/issues/21, as that will increase the amount of work further.

This is functionality the stats runner has to split the loop step by file, and distribute the work between multiple processes: https://github.com/codeforIATI/IATI-Stats/blob/main/statsrunner/loop.py#L167-L172. I've set this to 2, as GitHub actions gets access to 2 cores.

**Comment by andylolz** [comment]
Okay nice, sounds good.

Ahhh – I see you’ve tried it on dev, and it looks like it makes a big improvement to the workflow run time! That’s fab, let’s definitely get this merged

**Review by andylolz — APPROVED** [review]

**Comment by andylolz** [comment]
(Thanks also for explaining this Ben!)

**Pull request merged**
